### ISSUE TITLE
Add code coverage

### ISSUE THREAD

**Issue by Luni-4** [sifis-home/wp3-solutions#6]
It is necessary to evaluate the code coverage of this repository. 

- About Java code coverage: https://en.wikipedia.org/wiki/Java_code_coverage_tools
- An article that explains code coverage in `maven`: https://www.lambdatest.com/blog/reporting-code-coverage-using-maven-and-jacoco-plugin/
- An article that explains how to produce code coverage report with GitHub Actions and upload it to `coveralls` in order to access and see that in a better way: https://hyp0th3rmi4.medium.com/configuring-coveralls-io-reports-for-maven-builds-with-github-actions-393b11fa3402

**Comment by rikard-sics** [comment]
Thanks for the resources, I will start taking a look at this.

**Comment by rikard-sics** [comment]
I have now added functionality using Github actions so that code coverage reports are automatically generated by Jacoco and deployed on Github pages. The link to the code coverage reports can be found at the bottom of the README.
