### ISSUE TITLE
Create a Dockerfile

### ISSUE THREAD

**Issue by Luni-4** [sifis-home/wp3-solutions#7]
Write a `Dockerfile` that allows to run the code on each machine avoiding dependency problems:

What it is necessary:

1. Create the image with `docker build -t wp3-solution -f Dockerfile`
2. Pass the various inputs through `docker run -t wp3-solution`

About Docker: https://docs.docker.com/engine/reference/commandline/build/ and https://docs.docker.com/engine/reference/run/#docker-run-reference

Use the image to run tests on GitHub Actions, so both of them are tested without wasting resources, both the `docker build` and the `docker run` phases.

**Comment by rikard-sics** [comment]
Practical steps:
1. Create Dockerfile script (clone Github, place in folder, import from folder)
2. Pass arguments (if necessary)

See:
https://github.com/sifis-home/wp4-aud_manager/blob/master/Dockerfile
https://github.com/sifis-home/Device_Anomaly_Detection/blob/master/Dockerfile

**Comment by rikard-sics** [comment]
The script _build-for-docker.sh_ can be used to build Dockerfiles for the solutions (EDHOC and Group Applications). It can also build the actual Docker Images by specifying the flag _--build-images_.

In addition there is a Github Action that automatically builds Docker Images for the solutions and pushes them to Docker Hub.
